version: '3'
services:
  api:
    image: 'ieetec/hmidataadquisition'
    build: .
    env_file:
      - .env
    ports:
      - "80:8080"
  ftp:
    image: delfer/alpine-ftp-server
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - USERS=${FTP_USER}|${FTP_PASSWORD}