name: Nodejs CI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: 
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS 16.13.1
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.1
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/hmiFileSync.exe
      