name: Nodejs CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS 16.13.1
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.1
      - run: npm run build
      